
version: '3' # versão do yaml

services: # representam os containers
  ngcashapp: # nome do serviço
    image: postgres # imagem que o docker irá se basear para criar o container
    environment: # variáveis de ambiente
      POSTGRES_PASSWORD: 'postgres'
    container_name: ngcashapp # nome do container
    
    ports: # portas para acessar o container
      - '5432:5432'
    volumes: # onde serão armazenadas as informações do banco
      - .docker/dbdata:/var/lib/postgresql/data
